import { MCListing, User } from '../types'

// Mock users
export const mockSellers: User[] = [
  {
    id: '1',
    email: 'john@example.com',
    name: 'John Smith',
    role: 'seller',
    verified: true,
    trustScore: 92,
    memberSince: new Date('2022-01-15'),
    completedDeals: 12,
    reviews: [],
    identityVerified: false
  },
  {
    id: '2',
    email: 'sarah@example.com',
    name: 'Sarah Johnson',
    role: 'seller',
    verified: true,
    trustScore: 88,
    memberSince: new Date('2021-06-20'),
    completedDeals: 18,
    reviews: [],
    identityVerified: false
  }
]

// Mock MC listings
export const mockListings: MCListing[] = [
  {
    id: '1',
    mcNumber: '123456',
    sellerId: '1',
    seller: mockSellers[0],
    title: 'Established Dry Van Authority - Clean Record',
    description: 'Well-maintained authority with 8 years of operation. Perfect safety record, all insurance current. Ready for immediate transfer.',
    price: 45000,
    trustScore: 92,
    trustLevel: 'high',
    verified: true,
    verificationBadges: ['Insurance Verified', 'Safety Rating Confirmed', 'Documents Complete'],
    yearsActive: 8,
    operationType: ['Dry Van', 'Interstate', 'Intrastate'],
    fleetSize: 15,
    safetyRating: 'satisfactory',
    insuranceStatus: 'active',
    documents: [],
    status: 'active',
    visibility: 'public',
    views: 234,
    saves: 18,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    // New fields
    state: 'TX',
    amazonStatus: 'active',
    amazonRelayScore: 'A',
    highwaySetup: true,
    sellingWithEmail: true,
    sellingWithPhone: true,
    isPremium: false,
    isVip: false
  },
  {
    id: '2',
    mcNumber: '789012',
    sellerId: '2',
    seller: mockSellers[1],
    title: 'Reefer Authority with Regional Routes',
    description: 'Established reefer operation serving the Midwest. Strong customer base, excellent compliance history.',
    price: 62000,
    trustScore: 88,
    trustLevel: 'high',
    verified: true,
    verificationBadges: ['Insurance Verified', 'Safety Rating Confirmed'],
    yearsActive: 12,
    operationType: ['Reefer', 'Regional', 'Interstate'],
    fleetSize: 22,
    safetyRating: 'satisfactory',
    insuranceStatus: 'active',
    documents: [],
    status: 'active',
    visibility: 'public',
    views: 189,
    saves: 24,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    // New fields
    state: 'IL',
    amazonStatus: 'active',
    amazonRelayScore: 'B',
    highwaySetup: true,
    sellingWithEmail: true,
    sellingWithPhone: false,
    isPremium: true,
    isVip: false
  },
  {
    id: '3',
    mcNumber: '345678',
    sellerId: '1',
    seller: mockSellers[0],
    title: 'Flatbed & Heavy Haul Specialist',
    description: 'Specialized flatbed and heavy haul authority. All permits and bonding in place. Strong reputation.',
    price: 78000,
    trustScore: 95,
    trustLevel: 'high',
    verified: true,
    verificationBadges: ['Insurance Verified', 'Safety Rating Confirmed', 'Documents Complete', 'Premium Seller'],
    yearsActive: 15,
    operationType: ['Flatbed', 'Heavy Haul', 'Oversized', 'Interstate'],
    fleetSize: 18,
    safetyRating: 'satisfactory',
    insuranceStatus: 'active',
    documents: [],
    status: 'active',
    visibility: 'public',
    views: 312,
    saves: 41,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    // New fields
    state: 'CA',
    amazonStatus: 'none',
    amazonRelayScore: null,
    highwaySetup: true,
    sellingWithEmail: true,
    sellingWithPhone: true,
    isPremium: true,
    isVip: false
  },
  {
    id: '4',
    mcNumber: '567890',
    sellerId: '2',
    seller: mockSellers[1],
    title: 'Growing LTL Authority - West Coast',
    description: 'Less-than-truckload authority with established West Coast routes. Clean safety record.',
    price: 38000,
    trustScore: 76,
    trustLevel: 'medium',
    verified: true,
    verificationBadges: ['Insurance Verified', 'Safety Rating Confirmed'],
    yearsActive: 5,
    operationType: ['LTL', 'Regional', 'Dry Van'],
    fleetSize: 8,
    safetyRating: 'satisfactory',
    insuranceStatus: 'active',
    documents: [],
    status: 'active',
    visibility: 'public',
    views: 145,
    saves: 12,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    // New fields
    state: 'WA',
    amazonStatus: 'pending',
    amazonRelayScore: null,
    highwaySetup: false,
    sellingWithEmail: false,
    sellingWithPhone: true,
    isPremium: false,
    isVip: false
  },
  {
    id: '5',
    mcNumber: '901234',
    sellerId: '1',
    seller: mockSellers[0],
    title: 'Box Truck Authority - Local Delivery',
    description: 'Local delivery authority with box trucks. Great for Amazon and other delivery contracts.',
    price: 28000,
    trustScore: 82,
    trustLevel: 'high',
    verified: true,
    verificationBadges: ['Insurance Verified', 'Documents Complete'],
    yearsActive: 4,
    operationType: ['Box Truck', 'Local', 'Intrastate'],
    fleetSize: 12,
    safetyRating: 'satisfactory',
    insuranceStatus: 'active',
    documents: [],
    status: 'active',
    visibility: 'public',
    views: 98,
    saves: 9,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    // New fields
    state: 'FL',
    amazonStatus: 'active',
    amazonRelayScore: 'A',
    highwaySetup: true,
    sellingWithEmail: true,
    sellingWithPhone: true,
    isPremium: false,
    isVip: false
  },
  {
    id: '6',
    mcNumber: '234567',
    sellerId: '2',
    seller: mockSellers[1],
    title: 'Tanker Authority - Hazmat Certified',
    description: 'Tanker authority with full hazmat certification. Excellent safety record and compliance.',
    price: 85000,
    trustScore: 90,
    trustLevel: 'high',
    verified: true,
    verificationBadges: ['Insurance Verified', 'Safety Rating Confirmed', 'Hazmat Certified', 'Documents Complete'],
    yearsActive: 10,
    operationType: ['Tanker', 'Hazmat', 'Interstate'],
    fleetSize: 14,
    safetyRating: 'satisfactory',
    insuranceStatus: 'active',
    documents: [],
    status: 'active',
    visibility: 'public',
    views: 276,
    saves: 33,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
    // New fields
    state: 'OH',
    amazonStatus: 'suspended',
    amazonRelayScore: 'D',
    highwaySetup: true,
    sellingWithEmail: true,
    sellingWithPhone: false,
    isPremium: true,
    isVip: false
  }
]
